name: elestir_gelistir
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  package_info_plus: ^8.3.0
  flutter_email_sender: ^7.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/default_icon.png"

flutter_native_splash:
  color: "#FB8C00"
  image: assets/default_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/posts.json
